spring:
  cloud:
    bus:
      trace:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
# 优雅停机
server:
  shutdown: graceful
# 配置项加密密钥默认配置
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:Pa55w0rd@opensabre}
# opensabre framework配置
opensabre:
  sensitive:
    log:
      enabled: false # 日志脱敏开关，默认关闭
      rules: mobile,idCard,phone
  rest:
    result:
      framework:
        excludes: org.springdoc  # 统一报文排除的包名，该包下的rest不使用统一报文，框架内置
      excludes:                  # 统一报文排除的包名，该包下的rest不使用统一报文，应用级配置
# 日志相关
logging:
  level:
    io.github.opensabre: info
  logback:
    rollingpolicy:
      max-file-size: 1GB
  file:
    path: logs/
  config: classpath:logback-opensabre.xml
