#==============springboot相关配置===============#
spring.jackson.time-zone=GMT+8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8000/oauth2/jwks
#==============server相关配置===============#
server.shutdown=graceful
#==============敏感信息加密配置===============#
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:Pa55w0rd@opensabre}
#==============管理端点===============#
#启用配置里的info开头的变量
management.info.env.enabled=true
info.name=${spring.application.name}
info.application.version=${git.build.version}
info.java.version=${java.version}
info.opensabre.version=${opensabre.version}
info.opensabre.cloud.az=${opensabre.cloud.az}
info.opensabre.cloud.region=${opensabre.cloud.region}
#==============脱敏===============#
opensabre.sensitive.log.enabled=false
opensabre.sensitive.log.rules=mobile,idCard,phone
