spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
    #password: ${REDIS_PASSWORD:123456}
  jackson:
    time-zone: GMT+8

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hidePackages: io.github.opensabre
  local:
    # 默认5分钟本地缓存
    default:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 300000
      expireAfterAccessInMillis: 180000
    # 長時本地緩存1小时，主要用于要求时效一般
    longTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 3600000
      expireAfterAccessInMillis: 1800000
    # 短時本地緩存1分钟，主要用于要求时效较高的配置
    shortTime:
      type: caffeine
      keyConvertor: fastjson
      expireAfterWriteInMillis: 60000
      expireAfterAccessInMillis: 40000
  remote:
    # 默认2小时的远程缓存
    default:
      type: redis.lettuce
      expireAfterWriteInMillis: 7200000
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
    # 长时远程緩存12小时，主要用于要求时效要求一般的集中式缓存
    longTime:
      type: redis.lettuce
      expireAfterWriteInMillis: 43200000
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}
    # 短時远程緩存5分钟，主要用于要求时效较高的集中式缓存
    shortTime:
      type: redis.lettuce
      expireAfterWriteInMillis: 300000
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}