<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>opensabre-framework</artifactId>
        <groupId>io.github.opensabre</groupId>
        <version>${revision}</version>
    </parent>

    <artifactId>opensabre-starter-governance</artifactId>
    <packaging>jar</packaging>

    <name>opensabre-starter-governance</name>
    <description>Opensabre governance starter for audit and rate limit annotations</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.opensabre</groupId>
                <artifactId>opensabre-base-dependencies</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-eda</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-rpc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-cache</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
