spring:
  cloud:
    bus:
      trace:
        enabled: true
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8

logging:
  level:
    io.github.opensabre: info
  logback:
    rollingpolicy:
      max-file-size: 1GB
  file:
    path: logs/

