feign:
  circuitbreaker:
    enabled: true
  sentinel:
    enabled: true
  httpclient:
    hc5:
      enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: BASIC
spring:
  cloud:
    sentinel:
      enabled: true