#==============Spring MVC相关配置===============#
spring.web.resources.add-mappings=true
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
spring.mvc.format.date=yyyy-MM-dd
spring.servlet.multipart.max-request-size=2MB
spring.servlet.multipart.max-file-size=5MB
#==============Rest报文===============#
opensabre.rest.result.framework.excludes=org.springdoc
opensabre.rest.result.excludes=
#==============Rest Swagger文档===============#
opensabre.rest.swagger.version=v0.0.1
opensabre.rest.swagger.title=Opensabre API
opensabre.rest.swagger.description=Opensabre REST API
opensabre.rest.swagger.licenseUrl=https://github.com/opensabre/opensabre-framework
opensabre.rest.swagger.licenseName=Apache 2.0
opensabre.rest.swagger.wikiUrl=https://opensabre.github.io/docs
opensabre.rest.swagger.wikiDocumentation=Opensabre Wiki Documentation
# knife4j的增强配置
knife4j.enable=true
knife4j.setting.language=zh_cn
