name: Java CI
# 触发脚本的事件  这里为push代码之后触发
on: [push]
# 定义一个发行任务
jobs:
  build:
    # 任务运行的环境
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['21', '25']
    # 任务的步骤
    steps:
      # 1. 声明 checkout 仓库代码到工作区
    - uses: actions/checkout@v4
      # 2. 安装Java 环境 这里会用到的参数就是 Git Action secrets中配置的，
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: temurin
        cache: maven
      # 3.编译打包
    - name: Verify with Maven
      run: mvn -B verify javadoc:javadoc --file pom.xml
