<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.opensabre</groupId>
        <artifactId>opensabre-framework</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>opensabre-starter-security</artifactId>
    <packaging>jar</packaging>
    <name>opensabre-starter-security</name>
    <description>OpenSabre internal token security starter</description>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.opensabre</groupId>
                <artifactId>opensabre-base-dependencies</artifactId>
                <version>${revision}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-boot</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-starter-config</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.opensabre</groupId>
            <artifactId>opensabre-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-web</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
